module.exports = [
  {
    "numero": 1,
    "codigo": "ABEJA_AMARILLO_AMARILLO",
    "animal": "ABEJA",
    "colorCabeza": "AMARILLO",
    "tipoCerebro": "PENSANTE",
    "colorPecho": "AMARILLO",
    "tipoComunicacion": "LOGICO",
    "nombre": "ABEJA PENSANTE LÓGICO",
    "imagenUrl": "/images/personalidades/abeja_amarillo_amarillo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 2,
    "codigo": "ABEJA_AZUL_AMARILLO",
    "animal": "ABEJA",
    "colorCabeza": "AZUL",
    "tipoCerebro": "EMOCIONAL",
    "colorPecho": "AMARILLO",
    "tipoComunicacion": "LOGICO",
    "nombre": "ABEJA EMOCIONAL LÓGICO",
    "imagenUrl": "/images/personalidades/abeja_azul_amarillo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 3,
    "codigo": "ABEJA_ROJO_AMARILLO",
    "animal": "ABEJA",
    "colorCabeza": "ROJO",
    "tipoCerebro": "REPTILIANO",
    "colorPecho": "AMARILLO",
    "tipoComunicacion": "LOGICO",
    "nombre": "ABEJA REPTILIANO LÓGICO",
    "imagenUrl": "/images/personalidades/abeja_rojo_amarillo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 4,
    "codigo": "ABEJA_AMARILLO_AZUL",
    "animal": "ABEJA",
    "colorCabeza": "AMARILLO",
    "tipoCerebro": "PENSANTE",
    "colorPecho": "AZUL",
    "tipoComunicacion": "EMOCIONAL",
    "nombre": "ABEJA PENSANTE EMOCIONAL",
    "imagenUrl": "/images/personalidades/abeja_amarillo_azul.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 5,
    "codigo": "ABEJA_AZUL_AZUL",
    "animal": "ABEJA",
    "colorCabeza": "AZUL",
    "tipoCerebro": "EMOCIONAL",
    "colorPecho": "AZUL",
    "tipoComunicacion": "EMOCIONAL",
    "nombre": "ABEJA EMOCIONAL EMOCIONAL",
    "imagenUrl": "/images/personalidades/abeja_azul_azul.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 6,
    "codigo": "ABEJA_ROJO_AZUL",
    "animal": "ABEJA",
    "colorCabeza": "ROJO",
    "tipoCerebro": "REPTILIANO",
    "colorPecho": "AZUL",
    "tipoComunicacion": "EMOCIONAL",
    "nombre": "ABEJA REPTILIANO EMOCIONAL",
    "imagenUrl": "/images/personalidades/abeja_rojo_azul.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 7,
    "codigo": "ABEJA_AMARILLO_ROJO",
    "animal": "ABEJA",
    "colorCabeza": "AMARILLO",
    "tipoCerebro": "PENSANTE",
    "colorPecho": "ROJO",
    "tipoComunicacion": "RETADOR",
    "nombre": "ABEJA PENSANTE RETADOR",
    "imagenUrl": "/images/personalidades/abeja_amarillo_rojo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 8,
    "codigo": "ABEJA_AZUL_ROJO",
    "animal": "ABEJA",
    "colorCabeza": "AZUL",
    "tipoCerebro": "EMOCIONAL",
    "colorPecho": "ROJO",
    "tipoComunicacion": "RETADOR",
    "nombre": "ABEJA EMOCIONAL RETADOR",
    "imagenUrl": "/images/personalidades/abeja_azul_rojo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 9,
    "codigo": "ABEJA_ROJO_ROJO",
    "animal": "ABEJA",
    "colorCabeza": "ROJO",
    "tipoCerebro": "REPTILIANO",
    "colorPecho": "ROJO",
    "tipoComunicacion": "RETADOR",
    "nombre": "ABEJA REPTILIANO RETADOR",
    "imagenUrl": "/images/personalidades/abeja_rojo_rojo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 10,
    "codigo": "ABEJA_AMARILLO_VERDE",
    "animal": "ABEJA",
    "colorCabeza": "AMARILLO",
    "tipoCerebro": "PENSANTE",
    "colorPecho": "VERDE",
    "tipoComunicacion": "VISIONARIO",
    "nombre": "ABEJA PENSANTE VISIONARIO",
    "imagenUrl": "/images/personalidades/abeja_amarillo_verde.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 11,
    "codigo": "ABEJA_AZUL_VERDE",
    "animal": "ABEJA",
    "colorCabeza": "AZUL",
    "tipoCerebro": "EMOCIONAL",
    "colorPecho": "VERDE",
    "tipoComunicacion": "VISIONARIO",
    "nombre": "ABEJA EMOCIONAL VISIONARIO",
    "imagenUrl": "/images/personalidades/abeja_azul_verde.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 12,
    "codigo": "ABEJA_ROJO_VERDE",
    "animal": "ABEJA",
    "colorCabeza": "ROJO",
    "tipoCerebro": "REPTILIANO",
    "colorPecho": "VERDE",
    "tipoComunicacion": "VISIONARIO",
    "nombre": "ABEJA REPTILIANO VISIONARIO",
    "imagenUrl": "/images/personalidades/abeja_rojo_verde.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 13,
    "codigo": "DELFIN_AMARILLO_AMARILLO",
    "animal": "DELFIN",
    "colorCabeza": "AMARILLO",
    "tipoCerebro": "PENSANTE",
    "colorPecho": "AMARILLO",
    "tipoComunicacion": "LOGICO",
    "nombre": "DELFIN PENSANTE LÓGICO",
    "imagenUrl": "/images/personalidades/delfin_amarillo_amarillo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 14,
    "codigo": "DELFIN_AZUL_AMARILLO",
    "animal": "DELFIN",
    "colorCabeza": "AZUL",
    "tipoCerebro": "EMOCIONAL",
    "colorPecho": "AMARILLO",
    "tipoComunicacion": "LOGICO",
    "nombre": "DELFIN EMOCIONAL LÓGICO",
    "imagenUrl": "/images/personalidades/delfin_azul_amarillo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 15,
    "codigo": "DELFIN_ROJO_AMARILLO",
    "animal": "DELFIN",
    "colorCabeza": "ROJO",
    "tipoCerebro": "REPTILIANO",
    "colorPecho": "AMARILLO",
    "tipoComunicacion": "LOGICO",
    "nombre": "DELFIN REPTILIANO LÓGICO",
    "imagenUrl": "/images/personalidades/delfin_rojo_amarillo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 16,
    "codigo": "DELFIN_AMARILLO_AZUL",
    "animal": "DELFIN",
    "colorCabeza": "AMARILLO",
    "tipoCerebro": "PENSANTE",
    "colorPecho": "AZUL",
    "tipoComunicacion": "EMOCIONAL",
    "nombre": "DELFIN PENSANTE EMOCIONAL",
    "imagenUrl": "/images/personalidades/delfin_amarillo_azul.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 17,
    "codigo": "DELFIN_AZUL_AZUL",
    "animal": "DELFIN",
    "colorCabeza": "AZUL",
    "tipoCerebro": "EMOCIONAL",
    "colorPecho": "AZUL",
    "tipoComunicacion": "EMOCIONAL",
    "nombre": "DELFIN EMOCIONAL EMOCIONAL",
    "imagenUrl": "/images/personalidades/delfin_azul_azul.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 18,
    "codigo": "DELFIN_ROJO_AZUL",
    "animal": "DELFIN",
    "colorCabeza": "ROJO",
    "tipoCerebro": "REPTILIANO",
    "colorPecho": "AZUL",
    "tipoComunicacion": "EMOCIONAL",
    "nombre": "DELFIN REPTILIANO EMOCIONAL",
    "imagenUrl": "/images/personalidades/delfin_rojo_azul.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 19,
    "codigo": "DELFIN_AMARILLO_ROJO",
    "animal": "DELFIN",
    "colorCabeza": "AMARILLO",
    "tipoCerebro": "PENSANTE",
    "colorPecho": "ROJO",
    "tipoComunicacion": "RETADOR",
    "nombre": "DELFIN PENSANTE RETADOR",
    "imagenUrl": "/images/personalidades/delfin_amarillo_rojo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 20,
    "codigo": "DELFIN_AZUL_ROJO",
    "animal": "DELFIN",
    "colorCabeza": "AZUL",
    "tipoCerebro": "EMOCIONAL",
    "colorPecho": "ROJO",
    "tipoComunicacion": "RETADOR",
    "nombre": "DELFIN EMOCIONAL RETADOR",
    "imagenUrl": "/images/personalidades/delfin_azul_rojo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 21,
    "codigo": "DELFIN_ROJO_ROJO",
    "animal": "DELFIN",
    "colorCabeza": "ROJO",
    "tipoCerebro": "REPTILIANO",
    "colorPecho": "ROJO",
    "tipoComunicacion": "RETADOR",
    "nombre": "DELFIN REPTILIANO RETADOR",
    "imagenUrl": "/images/personalidades/delfin_rojo_rojo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 22,
    "codigo": "DELFIN_AMARILLO_VERDE",
    "animal": "DELFIN",
    "colorCabeza": "AMARILLO",
    "tipoCerebro": "PENSANTE",
    "colorPecho": "VERDE",
    "tipoComunicacion": "VISIONARIO",
    "nombre": "DELFIN PENSANTE VISIONARIO",
    "imagenUrl": "/images/personalidades/delfin_amarillo_verde.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 23,
    "codigo": "DELFIN_AZUL_VERDE",
    "animal": "DELFIN",
    "colorCabeza": "AZUL",
    "tipoCerebro": "EMOCIONAL",
    "colorPecho": "VERDE",
    "tipoComunicacion": "VISIONARIO",
    "nombre": "DELFIN EMOCIONAL VISIONARIO",
    "imagenUrl": "/images/personalidades/delfin_azul_verde.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 24,
    "codigo": "DELFIN_ROJO_VERDE",
    "animal": "DELFIN",
    "colorCabeza": "ROJO",
    "tipoCerebro": "REPTILIANO",
    "colorPecho": "VERDE",
    "tipoComunicacion": "VISIONARIO",
    "nombre": "DELFIN REPTILIANO VISIONARIO",
    "imagenUrl": "/images/personalidades/delfin_rojo_verde.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 25,
    "codigo": "CAMALEON_AMARILLO_AMARILLO",
    "animal": "CAMALEON",
    "colorCabeza": "AMARILLO",
    "tipoCerebro": "PENSANTE",
    "colorPecho": "AMARILLO",
    "tipoComunicacion": "LOGICO",
    "nombre": "CAMALEÓN PENSANTE LÓGICO",
    "imagenUrl": "/images/personalidades/camaleon_amarillo_amarillo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 26,
    "codigo": "CAMALEON_AZUL_AMARILLO",
    "animal": "CAMALEON",
    "colorCabeza": "AZUL",
    "tipoCerebro": "EMOCIONAL",
    "colorPecho": "AMARILLO",
    "tipoComunicacion": "LOGICO",
    "nombre": "CAMALEÓN EMOCIONAL LÓGICO",
    "imagenUrl": "/images/personalidades/camaleon_azul_amarillo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 27,
    "codigo": "CAMALEON_ROJO_AMARILLO",
    "animal": "CAMALEON",
    "colorCabeza": "ROJO",
    "tipoCerebro": "REPTILIANO",
    "colorPecho": "AMARILLO",
    "tipoComunicacion": "LOGICO",
    "nombre": "CAMALEÓN REPTILIANO LÓGICO",
    "imagenUrl": "/images/personalidades/camaleon_rojo_amarillo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 28,
    "codigo": "CAMALEON_AMARILLO_AZUL",
    "animal": "CAMALEON",
    "colorCabeza": "AMARILLO",
    "tipoCerebro": "PENSANTE",
    "colorPecho": "AZUL",
    "tipoComunicacion": "EMOCIONAL",
    "nombre": "CAMALEÓN PENSANTE EMOCIONAL",
    "imagenUrl": "/images/personalidades/camaleon_amarillo_azul.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 29,
    "codigo": "CAMALEON_AZUL_AZUL",
    "animal": "CAMALEON",
    "colorCabeza": "AZUL",
    "tipoCerebro": "EMOCIONAL",
    "colorPecho": "AZUL",
    "tipoComunicacion": "EMOCIONAL",
    "nombre": "CAMALEÓN EMOCIONAL EMOCIONAL",
    "imagenUrl": "/images/personalidades/camaleon_azul_azul.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 30,
    "codigo": "CAMALEON_ROJO_AZUL",
    "animal": "CAMALEON",
    "colorCabeza": "ROJO",
    "tipoCerebro": "REPTILIANO",
    "colorPecho": "AZUL",
    "tipoComunicacion": "EMOCIONAL",
    "nombre": "CAMALEÓN REPTILIANO EMOCIONAL",
    "imagenUrl": "/images/personalidades/camaleon_rojo_azul.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 31,
    "codigo": "CAMALEON_AMARILLO_ROJO",
    "animal": "CAMALEON",
    "colorCabeza": "AMARILLO",
    "tipoCerebro": "PENSANTE",
    "colorPecho": "ROJO",
    "tipoComunicacion": "RETADOR",
    "nombre": "CAMALEÓN PENSANTE RETADOR",
    "imagenUrl": "/images/personalidades/camaleon_amarillo_rojo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 32,
    "codigo": "CAMALEON_AZUL_ROJO",
    "animal": "CAMALEON",
    "colorCabeza": "AZUL",
    "tipoCerebro": "EMOCIONAL",
    "colorPecho": "ROJO",
    "tipoComunicacion": "RETADOR",
    "nombre": "CAMALEÓN EMOCIONAL RETADOR",
    "imagenUrl": "/images/personalidades/camaleon_azul_rojo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 33,
    "codigo": "CAMALEON_ROJO_ROJO",
    "animal": "CAMALEON",
    "colorCabeza": "ROJO",
    "tipoCerebro": "REPTILIANO",
    "colorPecho": "ROJO",
    "tipoComunicacion": "RETADOR",
    "nombre": "CAMALEÓN REPTILIANO RETADOR",
    "imagenUrl": "/images/personalidades/camaleon_rojo_rojo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 34,
    "codigo": "CAMALEON_AMARILLO_VERDE",
    "animal": "CAMALEON",
    "colorCabeza": "AMARILLO",
    "tipoCerebro": "PENSANTE",
    "colorPecho": "VERDE",
    "tipoComunicacion": "VISIONARIO",
    "nombre": "CAMALEÓN PENSANTE VISIONARIO",
    "imagenUrl": "/images/personalidades/camaleon_amarillo_verde.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 35,
    "codigo": "CAMALEON_AZUL_VERDE",
    "animal": "CAMALEON",
    "colorCabeza": "AZUL",
    "tipoCerebro": "EMOCIONAL",
    "colorPecho": "VERDE",
    "tipoComunicacion": "VISIONARIO",
    "nombre": "CAMALEÓN EMOCIONAL VISIONARIO",
    "imagenUrl": "/images/personalidades/camaleon_azul_verde.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 36,
    "codigo": "CAMALEON_ROJO_VERDE",
    "animal": "CAMALEON",
    "colorCabeza": "ROJO",
    "tipoCerebro": "REPTILIANO",
    "colorPecho": "VERDE",
    "tipoComunicacion": "VISIONARIO",
    "nombre": "CAMALEÓN REPTILIANO VISIONARIO",
    "imagenUrl": "/images/personalidades/camaleon_rojo_verde.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 37,
    "codigo": "CASTOR_AMARILLO_AMARILLO",
    "animal": "CASTOR",
    "colorCabeza": "AMARILLO",
    "tipoCerebro": "PENSANTE",
    "colorPecho": "AMARILLO",
    "tipoComunicacion": "LOGICO",
    "nombre": "CASTOR PENSANTE LÓGICO",
    "imagenUrl": "/images/personalidades/castor_amarillo_amarillo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 38,
    "codigo": "CASTOR_AZUL_AMARILLO",
    "animal": "CASTOR",
    "colorCabeza": "AZUL",
    "tipoCerebro": "EMOCIONAL",
    "colorPecho": "AMARILLO",
    "tipoComunicacion": "LOGICO",
    "nombre": "CASTOR EMOCIONAL LÓGICO",
    "imagenUrl": "/images/personalidades/castor_azul_amarillo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 39,
    "codigo": "CASTOR_ROJO_AMARILLO",
    "animal": "CASTOR",
    "colorCabeza": "ROJO",
    "tipoCerebro": "REPTILIANO",
    "colorPecho": "AMARILLO",
    "tipoComunicacion": "LOGICO",
    "nombre": "CASTOR REPTILIANO LÓGICO",
    "imagenUrl": "/images/personalidades/castor_rojo_amarillo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 40,
    "codigo": "CASTOR_AMARILLO_AZUL",
    "animal": "CASTOR",
    "colorCabeza": "AMARILLO",
    "tipoCerebro": "PENSANTE",
    "colorPecho": "AZUL",
    "tipoComunicacion": "EMOCIONAL",
    "nombre": "CASTOR PENSANTE EMOCIONAL",
    "imagenUrl": "/images/personalidades/castor_amarillo_azul.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 41,
    "codigo": "CASTOR_AZUL_AZUL",
    "animal": "CASTOR",
    "colorCabeza": "AZUL",
    "tipoCerebro": "EMOCIONAL",
    "colorPecho": "AZUL",
    "tipoComunicacion": "EMOCIONAL",
    "nombre": "CASTOR EMOCIONAL EMOCIONAL",
    "imagenUrl": "/images/personalidades/castor_azul_azul.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 42,
    "codigo": "CASTOR_ROJO_AZUL",
    "animal": "CASTOR",
    "colorCabeza": "ROJO",
    "tipoCerebro": "REPTILIANO",
    "colorPecho": "AZUL",
    "tipoComunicacion": "EMOCIONAL",
    "nombre": "CASTOR REPTILIANO EMOCIONAL",
    "imagenUrl": "/images/personalidades/castor_rojo_azul.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 43,
    "codigo": "CASTOR_AMARILLO_ROJO",
    "animal": "CASTOR",
    "colorCabeza": "AMARILLO",
    "tipoCerebro": "PENSANTE",
    "colorPecho": "ROJO",
    "tipoComunicacion": "RETADOR",
    "nombre": "CASTOR PENSANTE RETADOR",
    "imagenUrl": "/images/personalidades/castor_amarillo_rojo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 44,
    "codigo": "CASTOR_AZUL_ROJO",
    "animal": "CASTOR",
    "colorCabeza": "AZUL",
    "tipoCerebro": "EMOCIONAL",
    "colorPecho": "ROJO",
    "tipoComunicacion": "RETADOR",
    "nombre": "CASTOR EMOCIONAL RETADOR",
    "imagenUrl": "/images/personalidades/castor_azul_rojo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 45,
    "codigo": "CASTOR_ROJO_ROJO",
    "animal": "CASTOR",
    "colorCabeza": "ROJO",
    "tipoCerebro": "REPTILIANO",
    "colorPecho": "ROJO",
    "tipoComunicacion": "RETADOR",
    "nombre": "CASTOR REPTILIANO RETADOR",
    "imagenUrl": "/images/personalidades/castor_rojo_rojo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 46,
    "codigo": "CASTOR_AMARILLO_VERDE",
    "animal": "CASTOR",
    "colorCabeza": "AMARILLO",
    "tipoCerebro": "PENSANTE",
    "colorPecho": "VERDE",
    "tipoComunicacion": "VISIONARIO",
    "nombre": "CASTOR PENSANTE VISIONARIO",
    "imagenUrl": "/images/personalidades/castor_amarillo_verde.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 47,
    "codigo": "CASTOR_AZUL_VERDE",
    "animal": "CASTOR",
    "colorCabeza": "AZUL",
    "tipoCerebro": "EMOCIONAL",
    "colorPecho": "VERDE",
    "tipoComunicacion": "VISIONARIO",
    "nombre": "CASTOR EMOCIONAL VISIONARIO",
    "imagenUrl": "/images/personalidades/castor_azul_verde.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 48,
    "codigo": "CASTOR_ROJO_VERDE",
    "animal": "CASTOR",
    "colorCabeza": "ROJO",
    "tipoCerebro": "REPTILIANO",
    "colorPecho": "VERDE",
    "tipoComunicacion": "VISIONARIO",
    "nombre": "CASTOR REPTILIANO VISIONARIO",
    "imagenUrl": "/images/personalidades/castor_rojo_verde.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 49,
    "codigo": "BUHO_AMARILLO_AMARILLO",
    "animal": "BUHO",
    "colorCabeza": "AMARILLO",
    "tipoCerebro": "PENSANTE",
    "colorPecho": "AMARILLO",
    "tipoComunicacion": "LOGICO",
    "nombre": "BUHO PENSANTE LÓGICO",
    "imagenUrl": "/images/personalidades/buho_amarillo_amarillo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 50,
    "codigo": "BUHO_AZUL_AMARILLO",
    "animal": "BUHO",
    "colorCabeza": "AZUL",
    "tipoCerebro": "EMOCIONAL",
    "colorPecho": "AMARILLO",
    "tipoComunicacion": "LOGICO",
    "nombre": "BUHO EMOCIONAL LÓGICO",
    "imagenUrl": "/images/personalidades/buho_azul_amarillo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 51,
    "codigo": "BUHO_ROJO_AMARILLO",
    "animal": "BUHO",
    "colorCabeza": "ROJO",
    "tipoCerebro": "REPTILIANO",
    "colorPecho": "AMARILLO",
    "tipoComunicacion": "LOGICO",
    "nombre": "BUHO REPTILIANO LÓGICO",
    "imagenUrl": "/images/personalidades/buho_rojo_amarillo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 52,
    "codigo": "BUHO_AMARILLO_AZUL",
    "animal": "BUHO",
    "colorCabeza": "AMARILLO",
    "tipoCerebro": "PENSANTE",
    "colorPecho": "AZUL",
    "tipoComunicacion": "EMOCIONAL",
    "nombre": "BUHO PENSANTE EMOCIONAL",
    "imagenUrl": "/images/personalidades/buho_amarillo_azul.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 53,
    "codigo": "BUHO_AZUL_AZUL",
    "animal": "BUHO",
    "colorCabeza": "AZUL",
    "tipoCerebro": "EMOCIONAL",
    "colorPecho": "AZUL",
    "tipoComunicacion": "EMOCIONAL",
    "nombre": "BUHO EMOCIONAL EMOCIONAL",
    "imagenUrl": "/images/personalidades/buho_azul_azul.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 54,
    "codigo": "BUHO_ROJO_AZUL",
    "animal": "BUHO",
    "colorCabeza": "ROJO",
    "tipoCerebro": "REPTILIANO",
    "colorPecho": "AZUL",
    "tipoComunicacion": "EMOCIONAL",
    "nombre": "BUHO REPTILIANO EMOCIONAL",
    "imagenUrl": "/images/personalidades/buho_rojo_azul.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 55,
    "codigo": "BUHO_AMARILLO_ROJO",
    "animal": "BUHO",
    "colorCabeza": "AMARILLO",
    "tipoCerebro": "PENSANTE",
    "colorPecho": "ROJO",
    "tipoComunicacion": "RETADOR",
    "nombre": "BUHO PENSANTE RETADOR",
    "imagenUrl": "/images/personalidades/buho_amarillo_rojo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 56,
    "codigo": "BUHO_AZUL_ROJO",
    "animal": "BUHO",
    "colorCabeza": "AZUL",
    "tipoCerebro": "EMOCIONAL",
    "colorPecho": "ROJO",
    "tipoComunicacion": "RETADOR",
    "nombre": "BUHO EMOCIONAL RETADOR",
    "imagenUrl": "/images/personalidades/buho_azul_rojo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 57,
    "codigo": "BUHO_ROJO_ROJO",
    "animal": "BUHO",
    "colorCabeza": "ROJO",
    "tipoCerebro": "REPTILIANO",
    "colorPecho": "ROJO",
    "tipoComunicacion": "RETADOR",
    "nombre": "BUHO REPTILIANO RETADOR",
    "imagenUrl": "/images/personalidades/buho_rojo_rojo.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 58,
    "codigo": "BUHO_AMARILLO_VERDE",
    "animal": "BUHO",
    "colorCabeza": "AMARILLO",
    "tipoCerebro": "PENSANTE",
    "colorPecho": "VERDE",
    "tipoComunicacion": "VISIONARIO",
    "nombre": "BUHO PENSANTE VISIONARIO",
    "imagenUrl": "/images/personalidades/buho_amarillo_verde.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 59,
    "codigo": "BUHO_AZUL_VERDE",
    "animal": "BUHO",
    "colorCabeza": "AZUL",
    "tipoCerebro": "EMOCIONAL",
    "colorPecho": "VERDE",
    "tipoComunicacion": "VISIONARIO",
    "nombre": "BUHO EMOCIONAL VISIONARIO",
    "imagenUrl": "/images/personalidades/buho_azul_verde.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  },
  {
    "numero": 60,
    "codigo": "BUHO_ROJO_VERDE",
    "animal": "BUHO",
    "colorCabeza": "ROJO",
    "tipoCerebro": "REPTILIANO",
    "colorPecho": "VERDE",
    "tipoComunicacion": "VISIONARIO",
    "nombre": "BUHO REPTILIANO VISIONARIO",
    "imagenUrl": "/images/personalidades/buho_rojo_verde.png",
    "descripcion": null,
    "formaPensar": null,
    "formaAprender": null,
    "descripcionComunicacion": null,
    "activo": true
  }
];
